### ISSUE TITLE
Ios5 todos app storage problem 

### ISSUE THREAD

**Issue by hano** [mway-io/The-M-Project-Sample-Apps#2] opened 2011-10-30 08:44 UTC
Saving a todo item raises an error. http://the-m-project.org/apps/todos/

**Comment by josher19** [comment] 2012-02-17 05:21
This could be caused by the D8 minification. On Chrome 15 on Linux, I get the following console error:

```
Uncaught Error: Invalid dateString 'Feb 16, 2012 12:40 PM' passed to create().
```

on d8-0.1.5.min.js line 11

```
D8.create = function (a){var b="number"===typeof a?a:null;if(!b){if((b=/(\d{1,2})\.(\d{1,2})\.(\d{2,4})/.exec(a))&&b[1]&&b[2]&&b[3])a=a.split(" "),a=b[2]+"/"+b[1]+"/"+b[3]+(a[1]?" "+a[1]:"");else if((b=/(\d{2,4})-(\d{1,2})-(\d{1,2})/.exec(a))&&b[1]&&b[2]&&b[3]){a=a.split("T");a[1]=a[1]?a[1].replace(/([0-9]{2}:[0-9]{2})[0-9:\.]*Z/g," $1"):null;
var a=b[2]+"/"+b[3]+"/"+b[1]+(a[1]?" "+a[1]:""),c=-1*6E4*(new Date).getTimezoneOffset()}b=Date.parse(a)+c}
if(a&&!b)throw"Error: Invalid dateString '"+a+"' passed to create().";
if(!a)return D8.now();a=new D8;a.date=new Date(b);return a}
```

I expect that `var a` is hiding the `argument a`, causing `a` to be undefined thus throwing the error.
Changing 

```
var a=b[2]+"/"+b[3]+"/"+b[1]+(a[1]?" "+a[1]:"") 
```

to 

```
a=b[2]+"/"+b[3]+"/"+b[1]+(a[1]?" "+a[1]:"")
```

should clean it up.

Alternatively, changing:

```
c=D8.create(M.ViewManager.getView("newItemPage","date").value).getTimestamp()
```

to

```
c=Date.parse(M.ViewManager.getView("newItemPage","date").value)
```

would avoid this particular error message.

**Comment by josher19** [comment] 2012-02-17 05:57
Looks like the problem was an misplaced "var offset" in D8.create.

Fixed in: https://github.com/josher19/D8/blob/master/d8.js
Details in: https://github.com/panacodalabs/D8/pull/3

->> Josh W <<-

**Closed as completed** 2012-02-17 07:56 UTC
